FROM amazonlinux:2

# Actualizar el sistema operativo
RUN yum update -y

# Instalar Apache, Git y otros paquetes necesarios
RUN yum install -y httpd git mod_ssl curl

# Instalar mod_ldap y mod_authnz_ldap
RUN yum install -y mod_ldap mod_authnz_ldap httpd-devel

# Habilitar el módulo rewrite de Apache
RUN echo "LoadModule rewrite_module modules/mod_rewrite.so" >> /etc/httpd/conf/httpd.conf

# Eliminar archivos existentes en /var/www/html
RUN rm -rf /var/www/html/*

# Clonar el repositorio
RUN git clone https://github.com/ferminromero00/LDAP_TAREA.git /var/www/html/LDAP_TAREA

# Mover los archivos necesarios a /var/www/html
RUN cp -r /var/www/html/LDAP_TAREA/RestauranteAna/* /var/www/html/

# Configurar permisos para la web
RUN chown -R apache:apache /var/www/html && \
    chmod -R 755 /var/www/html

# Eliminar archivo de configuración SSL predeterminado que causa el error
RUN rm -f /etc/httpd/conf.d/ssl.conf

# Añadir configuración de escucha en el puerto 389
RUN echo 'Listen 389' >> /etc/httpd/conf/httpd.conf
RUN echo 'Listen 636' >> /etc/httpd/conf/httpd.conf

# Añadir configuración de Apache para /protegido
RUN echo '<VirtualHost *:80>' >> /etc/httpd/conf/httpd.conf
RUN echo '    DocumentRoot "/var/www/html"' >> /etc/httpd/conf/httpd.conf
RUN echo '    <Directory "/var/www/html">' >> /etc/httpd/conf/httpd.conf
RUN echo '        Require all granted' >> /etc/httpd/conf/httpd.conf
RUN echo '    </Directory>' >> /etc/httpd/conf/httpd.conf
RUN echo '    <Location "/protegido">' >> /etc/httpd/conf/httpd.conf
RUN echo '        AuthType Basic' >> /etc/httpd/conf/httpd.conf
RUN echo '        AuthName "LDAP Authentication"' >> /etc/httpd/conf/httpd.conf
RUN echo '        AuthBasicProvider ldap' >> /etc/httpd/conf/httpd.conf
RUN echo '        AuthLDAPURL "ldap://ldap-server.work.gd:389/ou=empleados,dc=ldap-server,dc=work,dc=gd?uid"' >> /etc/httpd/conf/httpd.conf
RUN echo '        AuthLDAPBindDN "cn=admin,dc=ldap-server,dc=work,dc=gd"' >> /etc/httpd/conf/httpd.conf
RUN echo '        AuthLDAPBindPassword "admin"' >> /etc/httpd/conf/httpd.conf
RUN echo '        Require valid-user' >> /etc/httpd/conf/httpd.conf
RUN echo '        ErrorDocument 401 /error.html' >> /etc/httpd/conf/httpd.conf
RUN echo '    </Location>' >> /etc/httpd/conf/httpd.conf
RUN echo '</VirtualHost>' >> /etc/httpd/conf/httpd.conf

# Exponer los puertos 80
EXPOSE 80

# Iniciar Apache en primer plano
CMD ["/usr/sbin/httpd", "-D", "FOREGROUND"]
