# Usar una imagen base de Amazon Linux 2
FROM amazonlinux:2

# Actualizar el sistema operativo
RUN yum update -y

# Instalar Apache, Node.js, Git y otros paquetes necesarios
RUN yum install -y httpd git mod_ssl curl

# Eliminar archivos existentes en /var/www/html
RUN rm -rf /var/www/html/*

# Clonar el repositorio
RUN git clone https://github.com/ferminromero00/LDAP_TAREA.git /var/www/html/LDAP_TAREA

# Mover los archivos necesarios a /var/www/html
RUN cp -r /var/www/html/LDAP_TAREA/* /var/www/html/

# Configurar permisos para la web
RUN chown -R apache:apache /var/www/html && \
    chmod -R 755 /var/www/html

# Eliminar archivo de configuración SSL predeterminado que causa el error
RUN rm -f /etc/httpd/conf.d/ssl.conf

# Exponer los puertos 80 y 443
EXPOSE 80

# Iniciar Apache en primer plano
CMD ["/usr/sbin/httpd", "-D", "FOREGROUND"]