FROM osixia/openldap:latest

# Establece variables de entorno para la configuración de LDAP
ENV LDAP_ORGANISATION="Ejemplo1" \
    LDAP_DOMAIN="ldap-server.work.gd." \
    LDAP_ADMIN_PASSWORD="admin"

RUN sed -i 's|http://deb.debian.org/debian buster|http://archive.debian.org/debian buster|g' /etc/apt/sources.list && \
    sed -i 's|http://security.debian.org/debian-security|http://archive.debian.org/debian-security|g' /etc/apt/sources.list && \
    apt-get update && \
    apt-get install -y ldap-utils && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*


# Exponer el puerto LDAP
EXPOSE 389 636