# Usar una imagen base de Amazon Linux 2
FROM amazonlinux:2

# Actualizar el sistema operativo
RUN yum update -y

# Instalar Apache, Node.js, Git y otros paquetes necesarios
RUN yum install -y httpd git mod_ssl curl

# Instalar mod_ldap y mod_authnz_ldap
RUN yum install -y mod_ldap mod_authnz_ldap

# Eliminar archivos existentes en /var/www/html
RUN rm -rf /var/www/html/*

# Clonar el repositorio
RUN git clone https://github.com/ferminromero00/LDAP_TAREA.git /var/www/html/LDAP_TAREA

# Mover los archivos necesarios a /var/www/html
RUN cp -r /var/www/html/LDAP_TAREA/RestauranteAna/* /var/www/html/

# Configurar permisos para la web
RUN chown -R apache:apache /var/www/html && \
    chmod -R 755 /var/www/html

# Eliminar archivo de configuración SSL predeterminado que causa el error
RUN rm -f /etc/httpd/conf.d/ssl.conf

# Añadir configuración de VirtualHost
RUN cat <<EOF > /etc/httpd/conf/httpd.conf
<VirtualHost *:80>
    ServerName 10.0.1.161
    DocumentRoot "/var/www/html"
    <Directory "/var/www/html">
        Require all granted
    </Directory>
    # Protegemos /admin con autenticación LDAP
    <Location /admin>
        AuthType Basic
        AuthName "Acceso Restringido"
        AuthBasicProvider ldap
        AuthLDAPURL "ldap://10.0.1.161:389/ou=empleados,dc=ldap-server,dc=work,dc=gd?uid"
        AuthLDAPBindDN "cn=admin,dc=ldap-server,dc=work,dc=gd"
        AuthLDAPBindPassword "admin"
        Require valid-user
    </Location>
</VirtualHost>
EOF

# Exponer los puertos 80 y 443
EXPOSE 80

# Iniciar Apache en primer plano
CMD ["/usr/sbin/httpd", "-D", "FOREGROUND"]